// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxSUBe5i11TnwENsGsS8U1eOKTxRukunw',
    appId: '1:685436522825:web:bf4198724b956a474f8a98',
    messagingSenderId: '685436522825',
    projectId: 'leisuresync-f8374',
    authDomain: 'leisuresync-f8374.firebaseapp.com',
    storageBucket: 'leisuresync-f8374.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GJ_fja828u8g0P4oBBG3TcBryBj-hA0',
    appId: '1:685436522825:android:5b164d389a8323374f8a98',
    messagingSenderId: '685436522825',
    projectId: 'leisuresync-f8374',
    storageBucket: 'leisuresync-f8374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcvBbFUYcf-xqQRf7hCohGPUoV26vZCJM',
    appId: '1:685436522825:ios:2025af74629e77e14f8a98',
    messagingSenderId: '685436522825',
    projectId: 'leisuresync-f8374',
    storageBucket: 'leisuresync-f8374.firebasestorage.app',
    iosBundleId: 'com.example.leisuresync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcvBbFUYcf-xqQRf7hCohGPUoV26vZCJM',
    appId: '1:685436522825:ios:2025af74629e77e14f8a98',
    messagingSenderId: '685436522825',
    projectId: 'leisuresync-f8374',
    storageBucket: 'leisuresync-f8374.firebasestorage.app',
    iosBundleId: 'com.example.leisuresync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxSUBe5i11TnwENsGsS8U1eOKTxRukunw',
    appId: '1:685436522825:web:331096de0e0af88f4f8a98',
    messagingSenderId: '685436522825',
    projectId: 'leisuresync-f8374',
    authDomain: 'leisuresync-f8374.firebaseapp.com',
    storageBucket: 'leisuresync-f8374.firebasestorage.app',
  );
}
